name: Lint

on: push

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
          architecture: 'x64'

      - name: Setup bundler
        run: gem install bundler -v 2.1.4 --no-doc

      - name: Setup gems
        run: bundle install --jobs 4

      - name: Run linters
        uses: samuelmeuli/lint-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          rubocop: true
          auto_fix: true
          git_email: 'ci@discourse'
