name: Push Clean

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!

    - name: debug
      run: cat /etc/apt/sources.list

    - name: debug2
      run: cat /etc/apt/apt.conf

    - name: apt
      run: sudo apt-get -yqq install jhead
